apiVersion: v1
kind: Config
clusters:
- name: "dev-test"
  cluster:
    server: "https://console.app.sof.intra/k8s/clusters/c-fll9m"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUczVENDQ\
      k1XZ0F3SUJBZ0lDRUFFd0RRWUpLb1pJaHZjTkFRRUxCUUF3Z2dFeE1Rc3dDUVlEVlFRR0V3SkMKV\
      WpFTE1Ba0dBMVVFQ0F3Q1JFWXhFVEFQQmdOVkJBY01DRUp5WVhOcGJHbGhNVEV3THdZRFZRUUtEQ\
      2hUWldOeQpaWFJoY21saElHUmxJRTl5WTJGdFpXNTBieUJHWldSbGNtRnNJQzBnVTA5R0wwMVFNV\
      DR3UEFZRFZRUUtERFZECmIyOXlaR1Z1WVdOaGJ5MUhaWEpoYkNCa1pTQlVaV051YjJ4dloybGhJR\
      1JoSUVsdVptOXliV0ZqWVc4Z0xTQkQKUjFSRlF6RXVNQ3dHQTFVRUN3d2xRMjl2Y21SbGJtRmpZV\
      zhnWkdVZ1NXNW1jbUZsYzNSeWRYUjFjbUVnTFNCRApUMGxPUmpFdE1Dc0dBMVVFQXd3a1FYVjBiM\
      0pwWkdGa1pTQkRaWEowYVdacFkyRmtiM0poSUZKaGFYb2dVMDlHCklIWXlNVEF3TGdZSktvWklod\
      mNOQVFrQkZpRnpaV2QxY21GdVkyRXRjMjltUUhCc1lXNWxhbUZ0Wlc1MGJ5NW4KYjNZdVluSXdIa\
      GNOTVRnd09ESXlNakEwTURBd1doY05NekF4TURBNE1qQTBNREF3V2pBOE1Ub3dPQVlEVlFRRApFe\
      kZCZFhSdmNtbGtZV1JsSUVObGNuUnBabWxqWVdSdmNtRWdaR1VnU1c1bWNtRkZjM1J5ZFhSMWNtR\
      WdVMDlHCklIWXlNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQWpQe\
      lpYYzBaNTdlenhmZW8KaktvalJ0M0lCcTVvTE85TUZvTDdaRmszVmd2YlZpYytQaEo5Qk5XbW9hK\
      2xVVTlvSnI0eTRWd2JWUGhxdHVoMwo5d1N4NlRrTnBMdWRmSmdHTXJLZTd4amJ4cXZIWXNlWXlMQ\
      lhINHREU2k5U3RCS1lMR016WFdDSDR4dG9JN0tmCnR6YmNyTkN3Ykk2dlFPVE84MjlIcWI3WnlyV\
      1RNWjBpeDQyWmtpckpZOGIwdXJUSFRHVWl5SUw4dk9pYkJIQzcKM0RUY0plUnVodEhxNlQ3ajBtT\
      FNlOHNESDRWakhHMGVRaUZzL1BlTGYrR0xMajR1empkdkRlNHp0eGhOM1IzegpScDluUENtb2I5Y\
      kVYbDhkVUY1TEV4VUVJbFpXekpJOUhWQ3lpY0hWaXFBS284VmJzd3EvSW1ja1h0MFRldnM4CmRTZ\
      UdvSWgxU3ZyL3BVQ2dVV2pXT3ZtTjFMMWVJZFRpYzhSWVlHZEpoWmFzcjRvbndsb2g0VVd3ZzZOV\
      1VnRVoKMXlGZklUU21EUzhEUlVkSXR6azIxeG9rVG4xeDJDKzVOUDMydGNXSmlWUWQvcmJadlhNM\
      0piMzM2RnVOdFBucwpFVi81eW5DNEdzcTdJZ1lmb3lxZENHMThPUy8rSGRzdHd3SUFhdzhlQlVqc\
      HcybzhRYVI1aUlOSEY5V2FoQTNSCkl5czRaZisxMzdvV0NOcFlJekcxTTIzQW53cEhhRXFZeHh5N\
      0RwVmpsbFdVUU1jVFFwZDlUS0p3MGZRR2Rra2YKNDFSdEhYUFZxdkNLMzlRVDBXMXowbCttbDFxd\
      lBFWVliZzhrWGRCQncvWFp5c0NXTkRYcTVzbXlrNHc1OE96bQpmRkZxWnZYWUJpUDlWd1VTREpPU\
      0RxTkwrYk1DQXdFQUFhT0I4VENCN2pBT0JnTlZIUThCQWY4RUJBTUNBUVl3CkVnWURWUjBUQVFIL\
      0JBZ3dCZ0VCL3dJQkFqQWRCZ05WSFE0RUZnUVVRaFZyRElFV24wUkdhY0JyTEM3clpTVUQKVVBNd\
      0h3WURWUjBqQkJnd0ZvQVV5UU5LZGNmVXpZeVF6Z1BoVTI0UHdZV3pjQlV3U1FZSUt3WUJCUVVIQ\
      VFFRQpQVEE3TURrR0NDc0dBUVVGQnpBQ2hpMW9kSFJ3T2k4dmNHdHBMbk52Wmk1cGJuUnlZUzlqW\
      lhKMGN5OWhZeTF5CllXbDZMWE52WmkxMk1pNWpjblF3UFFZRFZSMGZCRFl3TkRBeW9EQ2dMb1lzY\
      UhSMGNEb3ZMM0JyYVM1emIyWXUKYVc1MGNtRXZZM0pzY3k5aFl5MXlZV2w2TFhOdlppMTJNaTVqY\
      213d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQgpBRitmU081ZWFJYnBzTUV5ZHh3VitrczI5cHBaN\
      EFsQWpKRDIyMXM1OGFJMjRmNkxTMm4ra3lTNUNieXlrTG9ECkFObWF0ZDZKTUtEK3F5Nk1zL0lGa\
      UdlblZtR1k1WmZ3Ri85UzVqZUpMMFc3aUVRcnRuM3BDTlNuVTF2dzgxTmkKTzY1WE0vS1BZT01xb\
      FVtRmlxSHVGRUpFQ1Q4VStPWjJKVEFuK3Vic3VoS3NYOFhVMERzSXF2TGNycm1NL2VBVApOY3gxW\
      VRZYnhHU3hhNm4wTDEwSG95VDFFeGRZQ3k0NG1XbG8yTFJDZTAybGtidnRVdnVkR3pWdEk0R2k1O\
      EwvClArOU45R2pCNDBvWVd1cEx3YVVHaU1wVTBZZTJLMU00MXRWWjJ3S2loTjRjU08vNFZ6ZEdRc\
      nJweUt6a2NlM0EKd2l6M094Ny9ZRDdsRFRNL2JpSU9jV3l4dGtiZFg5YWp0SXJrNnA0U09NMTVPU\
      kJSRzNJRmlydnR3TTRoRGRoMgpCM0l4MXZOU1JJaWFmZjBVeGM2TDhnR1BXajB5NWdadjBKekZIT\
      DVwWjRyWTVRWDgrb3Vyd2hCS3pQOTBkajJmClpJZ0VDdXR2bVB2b29LS2N6ajZNMXgzU3BMeEVvd\
      mNGODNoeVhmVnN1Vml0Q3hnOE9laFRKNjcvMG9yQ09lNXUKdXUvNTI1M1pHS3drdmZ0NVBaVjd2N\
      2tOOE1hQmpKelpxODVTRXZVWnpMQWg0ME1sTnQwRkd6aS9ZWkhQaW05bApTczdEckFRekp2RjE2d\
      FZJMzJCbnJ1ci9iL2FUUjVqNnlXQm0vdWhKRlFIeFJQSlZWYi8xVXArelE5MTQ5aU1lCmZqWW9ZU\
      2dBeS96M1ZxRzg5Yy8zMHBOSlNZTjZOS3VlcGNsQU9kb0UrWlVqCi0tLS0tRU5EIENFUlRJRklDQ\
      VRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUgyRENDQmNDZ0F3SUJBZ0lKQ\
      UxTcW43elArbFNWTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUlCTVRFTE1Ba0cKQTFVRUJoTUNRbEl4Q\
      3pBSkJnTlZCQWdNQWtSR01SRXdEd1lEVlFRSERBaENjbUZ6YVd4cFlURXhNQzhHQTFVRQpDZ3dvV\
      TJWamNtVjBZWEpwWVNCa1pTQlBjbU5oYldWdWRHOGdSbVZrWlhKaGJDQXRJRk5QUmk5TlVERStNR\
      HdHCkExVUVDZ3cxUTI5dmNtUmxibUZqWVc4dFIyVnlZV3dnWkdVZ1ZHVmpibTlzYjJkcFlTQmtZU\
      0JKYm1admNtMWgKWTJGdklDMGdRMGRVUlVNeExqQXNCZ05WQkFzTUpVTnZiM0prWlc1aFkyRnZJR\
      1JsSUVsdVpuSmhaWE4wY25WMApkWEpoSUMwZ1EwOUpUa1l4TFRBckJnTlZCQU1NSkVGMWRHOXlhV\
      1JoWkdVZ1EyVnlkR2xtYVdOaFpHOXlZU0JTCllXbDZJRk5QUmlCMk1qRXdNQzRHQ1NxR1NJYjNEU\
      UVKQVJZaGMyVm5kWEpoYm1OaExYTnZaa0J3YkdGdVpXcGgKYldWdWRHOHVaMjkyTG1KeU1CNFhEV\
      EU0TURnd05qSXlNRGswTjFvWERUTXdNRGt5TWpJeU1EazBOMW93Z2dFeApNUXN3Q1FZRFZRUUdFd\
      0pDVWpFTE1Ba0dBMVVFQ0F3Q1JFWXhFVEFQQmdOVkJBY01DRUp5WVhOcGJHbGhNVEV3Ckx3WURWU\
      VFLRENoVFpXTnlaWFJoY21saElHUmxJRTl5WTJGdFpXNTBieUJHWldSbGNtRnNJQzBnVTA5R0wwM\
      VEKTVQ0d1BBWURWUVFLRERWRGIyOXlaR1Z1WVdOaGJ5MUhaWEpoYkNCa1pTQlVaV051YjJ4dloyb\
      GhJR1JoSUVsdQpabTl5YldGallXOGdMU0JEUjFSRlF6RXVNQ3dHQTFVRUN3d2xRMjl2Y21SbGJtR\
      mpZVzhnWkdVZ1NXNW1jbUZsCmMzUnlkWFIxY21FZ0xTQkRUMGxPUmpFdE1Dc0dBMVVFQXd3a1FYV\
      jBiM0pwWkdGa1pTQkRaWEowYVdacFkyRmsKYjNKaElGSmhhWG9nVTA5R0lIWXlNVEF3TGdZSktvW\
      klodmNOQVFrQkZpRnpaV2QxY21GdVkyRXRjMjltUUhCcwpZVzVsYW1GdFpXNTBieTVuYjNZdVluS\
      XdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDCkFRRGgvb2hDekFKL1ZoS\
      1JCTnV5YUhVcVgzME01ZGZJVk9kSnJtOHRUL25xNjFQdCt1VVNIT1FOWHN6TkxaY3oKZ2pER2g0V\
      zJ5aDhxcGFDTUYwd2ZvbTE2L1k1M1NnQm1KeitnU1lPNWY1bjNweGllSEVSeWhCRU8zZ0dNUmRMS\
      gpaQk5kbWNkOTNzbnlpdDVGUzMxa2JSS2drYnRXTXJBaFhEQzJIT09JREkrU1gwWk95MnZ6T3NlT\
      WJhWmtTdHFGCmJIcVhZclFsYm9tblZDRE5uTGxFSVdJT0xXaU5BZHQ4dzBocU54N1ZLcXl4VjRhd\
      HBsZXQyWTREZE9EeEJnSEoKVk5zY1ByYUZSMUJzVlN6YStIZHFYWGtCL2FLd002bDBYRzBtQUFZM\
      FZKWlovWS9iZ3NONVRCbUE3cjFNUlpNRQprM3dWUnJPVGdZWVhJU2swQjcrR2x1ZnRkcFNQOElSU\
      TJNZmFCNzdiS1FRVGpFaW5GSXdyV1lDK0xFZFV3L0xHClJDSzNXRk5RUXRKRk5DeG4raG1WQkpTS\
      lRCd0k4ckd3OHJMMDQ1Z2UyZWVpWmlBOHhsS1JwaVY2QXVDcjRONXoKVlkveGZxTUJCQWgrV08wZ\
      2UvVmQ1RDhQWFZNTHFha29OSnZyMmlRMGlIRXVnTlZqNEI1c2FNdkpETVZnRWl2UApPZDNUN0xwW\
      FB3eDg2aS9PSTV5ME9nYW9OdjllQlU1MS93TTV0UExramFiSHFVOVp3MW9qVllqa0Erdjl6dXFlC\
      lBkeit1OVRZVXVta3R2QkFDVk9Ca0N4NUxvYWhpSmpuVG1zZDl0djU5dFoxcGhEeTBvSndwY0JUZ\
      GUyUWtydkIKamVsYjNrbkI3UEJsQ0F2OUpZV2duUVhJS1R3VkZ3NzA0Mk5lY1lXMWFNNGxvUUlEQ\
      VFBQm80SHVNSUhyTUE0RwpBMVVkRHdFQi93UUVBd0lCaGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvT\
      UIwR0ExVWREZ1FXQkJUSkEwcDF4OVROCmpKRE9BK0ZUYmcvQmhiTndGVEFmQmdOVkhTTUVHREFXZ\
      0JUSkEwcDF4OVROakpET0ErRlRiZy9CaGJOd0ZUQkoKQmdnckJnRUZCUWNCQVFROU1Ec3dPUVlJS\
      3dZQkJRVUhNQUtHTFdoMGRIQTZMeTl3YTJrdWMyOW1MbWx1ZEhKaApMMk5sY25SekwyRmpMWEpoY\
      VhvdGMyOW1MWFl5TG1OeWREQTlCZ05WSFI4RU5qQTBNREtnTUtBdWhpeG9kSFJ3Ck9pOHZjR3RwT\
      G5OdlppNXBiblJ5WVM5amNteHpMMkZqTFhKaGFYb3RjMjltTFhZeUxtTnliREFOQmdrcWhraUcKO\
      XcwQkFRc0ZBQU9DQWdFQXY1OUZtNGViSEFFdDVpMDNMYnJKb0lpMTh0RzlmTk1nZW9RT25nWkhYa\
      klPK1lOSwpvRzhZSFlOTko0TE1aL1FvRHg2b0MzdU1IOXh5c3FncEVCa2Z2QVRQRUdUMTBhMlR2e\
      WxkWEdrYTgrWW1NSGgzCnR2LzNBbmlldEMzbnVvTHFia2k2L09LT3QvZ3FEQUQrM1RRYXVtS29uS\
      mdtUHlRTGROU2NWR3BuaWhUeENtbGgKZWd3RUVHbkN4WFpMaENUTkRERWE5T1NIREZSRWpNaWU5V\
      E5OUmg1SzVTcTMvNnlXTjdQNCt3VmhXMk0rRlptYQpmVWNtSFdmbGdmMENXeFpQaC9DK3BGWEc3d\
      WxYbkdsVU84SFJlVHlEeGtQVGw1NzNVT3V2b0M1L1ZKSkgvUGZkCk1yUDdpTHVZUjh2Ujl1VHlZV\
      nVTOUN5YXRBOHhFbEsvNGd0RlI2R0xydWFGSDVGNEQ3UUZsTjRZNjZWc1VqaXMKSko1UWVuUEVJW\
      HI4ZE9yWFRxb2NFQVhMN29rRjBCaEp6Rlc3cXJrdi83YkFUZXRVQ2p2VkVrVVVWaFdFY0tuZgo2c\
      lhZRkFNOTBPRkk5dTVBQU1MVXNTM25oRTloSE4wZi9kTEIrSmlieWFqRFBMcUdUZ3lIS3JVRGFWQ\
      2Q2M054CmM2UnFkblZiUG93RVhaamh3WnlGT2Z2RUxvT05kWloxamwwenlUWnB4YkFPYW0yd3Bab\
      EpUWk5WZXhkVE9sMWMKZHB6ZWRKWlJpZnRBS3Rnd2l5dUJ3VW1yNktaU0VyeFNQRk5CUkZGM0ZSV\
      Gg5RFVUTnVYZzhvS1N0VDRJbVdoNgpYemdiVEQxbzZ5cUUxWHBIRm1HZVFKYjYxUXVwOWR1ckNze\
      nNqaWtnakMzOEdGZmRTUnhUaHlVakxpQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
- name: "dev-test-tkbn10"
  cluster:
    server: "https://192.168.22.130:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURReU1qSXdOVFF4T0ZvWERUTXdNRFF5TURJd05UUXhPRm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5UNFFiVWJtZ2FECndheFVBUFNaUWk5Vmo5SVJQN3E4QlErVnBTZEsydkY3UXJyQU9IcHBCZ\
      XA4REc2bG12YTY1ck9DRUhRSWE1eGEKczFGWGxHdTlHMU9wTG5ZL0w3ZmF0SjNMaGcxMWZKaGo4a\
      FV1bFRaRWZYVlRTZXFvWEE5Z2Y1NnZETWNHYjFOOApWNUNISjhSWE5aS3NYb0RpREdVZ3l3cFQ3d\
      TBQc05DWkc4V3RVNXpkT1F2RFJLU0xZSTErMDFZZWczd0RWdnhTCkVpcUZSeXdjMTZQcW8xWDRVQ\
      lkrUTUvaXZoM3N0Z1doTGlIcGlqU04zMmZPbHAvK09VbFBMWkNBNy9EaHhOdkYKcVl5NTh2MVJLS\
      1htZkRUUjF0VmRCYmNKM2FMeE5UcDRaV21aT09FdmNoYlFOYU9EMVZxK3lJVjlIVDMvVWFDLwpub\
      EJFa29ielFVVUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS250cEN6aHY4QnpzZWlBSDFzTFQwN\
      DdzMCtSTkRPWGNwQmoKY0hOeFoxMFBGdXNvcEYyRkszdFM2ZURFckszemlZTDR0MVFzaUo5bTdCS\
      FZDWXFYNGV5Q3FiNGsrUnVJeFd0Uwp0eXFHMkFaNDNMMkEweldBMTlzTEFLbUtrdXhuVWg3bHk4O\
      GZURGlnMVNuZGpCQkRUUElHalgwZ2xHcUtWU2laCk94bUo2OER2VUl0OGRobHR3V1ZnMGFCS2E3S\
      zNSSWVYeEFRb1FHZy9mYm93bUp0eEdlUFRKUXdpOFkzek5DVjkKM2tHcVRGUTBvOUxkVkdkZVpHO\
      E0raEszR2VSbFpQTU9naCtjTXFFeDdXaGJtL2FVQ3RKZFB6OGg2aXBibmc4UwpzVUlPVjRTZXlxS\
      HlJbmJXMnZBUUxsTU9tYzBYTEw3cStHNHhiSG1UK2YxMnFmeWlqK3c9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "dev-test-tkbn11"
  cluster:
    server: "https://192.168.22.131:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURReU1qSXdOVFF4T0ZvWERUTXdNRFF5TURJd05UUXhPRm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5UNFFiVWJtZ2FECndheFVBUFNaUWk5Vmo5SVJQN3E4QlErVnBTZEsydkY3UXJyQU9IcHBCZ\
      XA4REc2bG12YTY1ck9DRUhRSWE1eGEKczFGWGxHdTlHMU9wTG5ZL0w3ZmF0SjNMaGcxMWZKaGo4a\
      FV1bFRaRWZYVlRTZXFvWEE5Z2Y1NnZETWNHYjFOOApWNUNISjhSWE5aS3NYb0RpREdVZ3l3cFQ3d\
      TBQc05DWkc4V3RVNXpkT1F2RFJLU0xZSTErMDFZZWczd0RWdnhTCkVpcUZSeXdjMTZQcW8xWDRVQ\
      lkrUTUvaXZoM3N0Z1doTGlIcGlqU04zMmZPbHAvK09VbFBMWkNBNy9EaHhOdkYKcVl5NTh2MVJLS\
      1htZkRUUjF0VmRCYmNKM2FMeE5UcDRaV21aT09FdmNoYlFOYU9EMVZxK3lJVjlIVDMvVWFDLwpub\
      EJFa29ielFVVUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS250cEN6aHY4QnpzZWlBSDFzTFQwN\
      DdzMCtSTkRPWGNwQmoKY0hOeFoxMFBGdXNvcEYyRkszdFM2ZURFckszemlZTDR0MVFzaUo5bTdCS\
      FZDWXFYNGV5Q3FiNGsrUnVJeFd0Uwp0eXFHMkFaNDNMMkEweldBMTlzTEFLbUtrdXhuVWg3bHk4O\
      GZURGlnMVNuZGpCQkRUUElHalgwZ2xHcUtWU2laCk94bUo2OER2VUl0OGRobHR3V1ZnMGFCS2E3S\
      zNSSWVYeEFRb1FHZy9mYm93bUp0eEdlUFRKUXdpOFkzek5DVjkKM2tHcVRGUTBvOUxkVkdkZVpHO\
      E0raEszR2VSbFpQTU9naCtjTXFFeDdXaGJtL2FVQ3RKZFB6OGg2aXBibmc4UwpzVUlPVjRTZXlxS\
      HlJbmJXMnZBUUxsTU9tYzBYTEw3cStHNHhiSG1UK2YxMnFmeWlqK3c9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "dev-test"
  user:
    token: "kubeconfig-u-7wpbttbjqd.c-fll9m:kn2wqntv8njrhv2bqkzhgt5nknd4hcsl5xgngkqns2zgxfbc8jpd7r"

contexts:
- name: "dev-test"
  context:
    user: "dev-test"
    cluster: "dev-test"
- name: "dev-test-tkbn10"
  context:
    user: "dev-test"
    cluster: "dev-test-tkbn10"
- name: "dev-test-tkbn11"
  context:
    user: "dev-test"
    cluster: "dev-test-tkbn11"

current-context: "dev-test"

